### ISSUE TITLE
Notes Field Handling

### ISSUE THREAD

**Issue by jakeanq** [openmodal/lvm_read#5]
`lvm_read` fails with the following error when encountering a LVM file with the optional `Notes` field:

``` Python
>>> lvm_read.read("UD6mmT1.lvm")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/lvm_read.py", line 116, in read
    lvm_data = _read_lvm_base(filename)
  File "/usr/lib/python3.5/site-packages/lvm_read.py", line 79, in _read_lvm_base
    seg_data.append([float(a.replace(lvm_data['Decimal_Separator'], '.')) for a in
UnboundLocalError: local variable 'seg_data' referenced before assignment
```

I have checked with the following file and narrowed it down to the `Notes` field.

```
LabVIEW Measurement 
Writer_Version  2
Reader_Version  2
Separator   Tab
Decimal_Separator   .
Multi_Headings  No
X_Columns   One
Time_Pref   Absolute
Operator    user
Date    2016/08/11
Time    14:37:48.201000213623046875
***End_of_Header*** 

Notes   X values guaranteed valid only for Dev0/Ai0                         
Channels    7                           
Samples 100 100 0   0   0   0   100 
Date    2016/08/11  2016/08/11  2016/08/11  2016/08/11  2016/08/11  2016/08/11  2016/08/11  
Time    15:37:48.375    15:37:48.375    15:37:48.375    15:37:48.375    15:37:48.375    15:37:48.375    15:37:48.375    
X_Dimension Time    Time    Time    Time    Time    Time    Time    
X0  0.0000000000000000E+0   0.0000000000000000E+0   0.0000000000000000E+0   0.0000000000000000E+0   0.0000000000000000E+0   0.0000000000000000E+0   0.0000000000000000E+0   
Delta_X 0.001000    0.001000    1.000000    1.000000    1.000000    1.000000    0.001000    
***End_of_Header***                             
X_Value Dev0/Ai0    Dev0/Ai2    Untitled    Untitled 1  Untitled 2  Untitled 3  Dev0/Ai0 1  Comment
0.000000    -0.011923   7.254639                    -0.011923
0.001000    -0.009206   7.254639                    -0.009206
0.002000    -0.014640   7.250977                    -0.014640
0.003000    -0.014640   7.250977                    -0.014640
0.004000    -0.014640   7.250977                    -0.014640
```

**Comment by jankoslavic** [comment]
Resolved on 18th of Aug 2016
